### ISSUE TITLE
Disable for textarea and input fields

### ISSUE THREAD

**Issue by danilowoz** [siddharthkp/show-keys#2]
I'd like to have some way to only show the keys in there is no textarea or input fields focused, as in my case it looks a little bit spammy, once I only to show some shortcuts in my document.

**Comment by siddharthkp** [comment]
That's interesting!

How do you feel about adding a flag on window/global to handle that?

`window.SHOW_KEYS_SKIP_INPUTS=true`

Keeps the default api as simple as an import

**Comment by danilowoz** [comment]
Yeah, it works for me!

**Comment by siddharthkp** [comment]
Done!  Update to [1.1.0](https://codesandbox.io/s/fervent-bose-zx2if?file=/src/App.js)
